const appData = () => {
  return [
    {
      id: 1,
      name: "Above",
      album: "Haikyuu",
      cover: "./data/images/above-haikyuu.jpg",
      audio: "./data/audio/above-haikyuu.mp3",
      active: true,
    },
    {
      id: 2,
      name: "Crossing Fields",
      album: "Swords Art Online",
      cover: "./data/images/crossing-fields-sword-art-online.jpg",
      audio: "./data/audio/crossing-fields-sword-art-online.mp3",
      active: false,
    },
    {
      id: 3,
      name: "Fly High",
      album: "Haikyuu",
      cover: "./data/images/fly-high-haikyuu.jpg",
      audio: "./data/audio/fly-high-haikyuu.mp3",
      active: false,
    },
    {
      id: 4,
      name: "Hikaru Nara",
      album: "Your Lie In April",
      cover: "./data/images/hikaru-nara-your-lie-in-april.jpg",
      audio: "./data/audio/hikaru-nara-your-lie-in-april.mp3",
      active: false,
    },
    {
      id: 5,
      name: "Kataware Doki",
      album: "Kimi No Nawa",
      cover: "./data/images/kataware-doki-kimi-no-nawa.jpg",
      audio: "./data/audio/kataware-doki-kimi-no-nawa.mp3",
      active: false,
    },
    {
      id: 6,
      name: "Saitama",
      album: "One Punch Man",
      cover: "./data/images/saitama-one-punch-man.jpg",
      audio: "./data/audio/saitama-one-punch-man.mp3",
      active: false,
    },
    {
      id: 7,
      name: "Secret Base",
      album: "AnoHana",
      cover: "./data/images/secret-base-anohana.jpg",
      audio: "./data/audio/secret-base-anohana.mp3",
      active: false,
    },
    {
      id: 8,
      name: "Tanjiro No Uta",
      album: "Demon Slayer",
      cover: "./data/images/tanjiro-no-uta-demon-slayer.jpg",
      audio: "./data/audio/tanjiro-no-uta-demon-slayer.mp3",
      active: false,
    },
    {
      id: 9,
      name: "Uso",
      album: "Fullmetal Alchemist",
      cover: "./data/images/uso-fullmetal-alchemist.jpg",
      audio: "./data/audio/uso-fullmetal-alchemist.mp3",
      active: false,
    },
    {
      id: 10,
      name: "Yamiyo",
      album: "Dororo",
      cover: "./data/images/yamiyo-dororo.jpg",
      audio: "./data/audio/yamiyo-dororo.mp3",
      active: false,
    },
    {
      id: 11,
      name: "You Say Run",
      album: "My Hero Academia",
      cover: "./data/images/you-say-run-my-hero-academia.jpg",
      audio: "./data/audio/you-say-run-my-hero-academia.mp3",
      active: false,
    },
  ];
};

export default appData;
